# Generated by Django 4.2.1 on 2023-05-24 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todoApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bothLetters', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('prio', models.CharField(choices=[('urgent', 'urgent'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=6)),
                ('date', models.DateField(default=todoApp.models.return_date_time)),
                ('created_at', models.DateField(default=datetime.datetime.today)),
                ('category', models.CharField(max_length=100)),
                ('progress', models.CharField(choices=[('todo', 'todo'), ('in Process', 'in Process'), ('done', 'done'), ('awaiting Feedback', 'awaiting Feedback')], default='todo', max_length=20)),
                ('contactNames', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('letters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.letters')),
            ],
        ),
    ]
