# Generated by Django 4.2.1 on 2023-05-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_letters_color_alter_task_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='letters',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='todoApp.letters'),
        ),
    ]
