# Generated by Django 4.2.1 on 2023-05-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_contact_alter_letters_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='letters',
        ),
        migrations.AddField(
            model_name='task',
            name='letters',
            field=models.ManyToManyField(blank=True, default='', null=True, to='todoApp.letters'),
        ),
    ]
