# Generated by Django 4.2.1 on 2023-05-26 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoApp', '0009_remove_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contactNames',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
