# Generated by Django 4.2.1 on 2023-05-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0010_alter_task_contactnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoApp.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contactNames',
            field=models.ManyToManyField(to='todoApp.users'),
        ),
    ]
