# Generated by Django 4.2.1 on 2023-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0012_alter_contact_phone_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='testmail@test.de', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
