# Generated by Django 4.2.1 on 2023-05-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0013_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subtask',
            name='state',
            field=models.CharField(choices=[('todo', 'todo'), ('done', 'done')], default='todo', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='todoApp.subtask'),
        ),
    ]
