# Generated by Django 4.2.1 on 2023-05-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0014_rename_title_subtask_name_subtask_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(blank=True, default='', null=True, to='todoApp.subtask'),
        ),
    ]
