# Generated by Django 4.2.1 on 2023-05-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0015_remove_task_subtask_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtask',
            new_name='subtasks',
        ),
    ]
