# Generated by Django 4.2.1 on 2023-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0016_rename_subtask_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
