# Generated by Django 4.2.1 on 2023-06-03 16:48

from django.db import migrations, models
import todoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0018_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(default=todoApp.models.return_date_time, max_length=12),
        ),
    ]
